### ISSUE TITLE
Errors while initializing an arc42 template

### ISSUE THREAD

**Issue by funkr** [docToolchain/docToolchain#199] opened 2018-10-07 20:06 UTC
## Expected behavior and actual behavior.
I failed to build the arc42 template

## Steps to reproduce the problem.
git clone --recursive https://github.com/docToolchain/docToolchain.git
rm -rf .git
rm -rf resources/asciidoctor-reveal.js/.git
cd docToolchain/

./gradlew -b init.gradle initArc42EN -PnewDocDir=arc42

./bin/doctoolchain arc42 generateHTML

:generateHTML FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':generateHTML' property 'sourceDir' during up-to-date check.
> Failed to create MD5 hash for file content.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

**Comment by rdmueller** [comment] 2018-10-08 05:16
thanx. I will look into this asap.

**Comment by rdmueller** [comment] 2018-10-08 05:20
as a workaround: it should be possible to download the asciidoc template directly from arc42.org and place it in the src/docs folder. but you then also have to update the config.

currently, I am in the process of checking all functionality and writing tutorials which will help a lot in the future...

**Comment by jakubjab** [comment] 2018-10-08 19:04
I have checked and unfortunatelly I cannot reproduce it on my Mac. I can try on Linux Tomorrow.

@funkr:
- Can you please specify the system you are using?
- Can you please try with additional options like `./bin/doctoolchain arc42 generateHTML --stacktrace --debug`
- Can you try if giving the absolute directory outside of the doctoolchain helps, something like `-PnewDocDir=/tmp/arc42`

**Comment by funkr** [comment] 2018-10-08 19:28
OS: Win 10 /64 bit
executing the commands on MINGW64
[error.log](https://github.com/docToolchain/docToolchain/files/2457422/error.log)
[out.log](https://github.com/docToolchain/docToolchain/files/2457423/out.log)


$ ./bin/doctoolchain /tmp/arc42 generateHTML
C:/Users/Olaf/AppData/Local/Temp/arc42/build/ppt/images
:generateHTML FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':generateHTML' property 'sourceDir' during up-to-date check.
> Failed to create MD5 hash for file content.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by rdmueller** [comment] 2018-10-08 20:20
@funkr why don't you use bash on ubuntu via WSL? I don't know if it will work better, but it would be the "Real Ubuntu"

I just gave it a try on Win 10 / 64 bit via ubuntu bash:

```
>~/dt-issue-199$ git clone --recursive https://github.com/docToolchain/docToolchain.git
Cloning into 'docToolchain'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 2278 (delta 37), reused 97 (delta 29), pack-reused 2154
Receiving objects: 100% (2278/2278), 12.97 MiB | 2.10 MiB/s, done.
Resolving deltas: 100% (1036/1036), done.
Checking connectivity... done.
Checking out files: 100% (170/170), done.
Submodule 'resources/asciidoctor-reveal.js' (https://github.com/asciidoctor/asciidoctor-reveal.js) registered for path 'resources/asciidoctor-reveal.js'
Submodule 'resources/reveal.js' (https://github.com/hakimel/reveal.js) registered for path 'resources/reveal.js'
Cloning into 'resources/asciidoctor-reveal.js'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 2253 (delta 1), reused 3 (delta 1), pack-reused 2245
Receiving objects: 100% (2253/2253), 3.64 MiB | 350.00 KiB/s, done.
Resolving deltas: 100% (1248/1248), done.
Checking connectivity... done.
Submodule path 'resources/asciidoctor-reveal.js': checked out '9667f5c5d926b3be48361d6d6413d3896954894c'
Cloning into 'resources/reveal.js'...
remote: Counting objects: 10790, done.
remote: Total 10790 (delta 0), reused 0 (delta 0), pack-reused 10790
Receiving objects: 100% (10790/10790), 8.15 MiB | 439.00 KiB/s, done.
Resolving deltas: 100% (5952/5952), done.
Checking connectivity... done.
Submodule path 'resources/reveal.js': checked out '539e774d31f91676bcc3f75e28168921cd27d819'>~/dt-issue-199$ cd docToolchain/
>~/dt-issue-199/docToolchain$ rm -rf .git
>~/dt-issue-199/docToolchain$ rm -rf resources/asciidoctor-reveal.js/.git
>~/dt-issue-199/docToolchain$ ./gradlew -b init.gradle initArc42EN -PnewDocDir=arc42
Starting a Gradle Daemon (subsequent builds will be faster)
Support for running Gradle using Java 7 has been deprecated and is scheduled to be removed in Gradle 5.0. Please see https://docs.gradle.org/4.3.1/userguide/java_plugin.html#sec:java_cross_compilation for more details.
Download https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-client/4.5.3/httpcomponents-client-4.5.3.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.pom
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcomponents-core/4.4.6/httpcomponents-core-4.4.6.pom
Download https://jcenter.bintray.com/de/undercouch/gradle-download-task/3.3.0/gradle-download-task-3.3.0.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar
Download https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar

> Configure project :
compiling with Java 1.7.0_191 at 20:15:35

Download https://github.com/arc42/arc42-template/raw/master/dist/arc42-template-EN-withhelp-asciidoc.zip

BUILD SUCCESSFUL in 1m 9s
2 actionable tasks: 2 executed
>~/dt-issue-199/docToolchain$ ./bin/doctoolchain arc42 generateHTML
Support for running Gradle using Java 7 has been deprecated and is scheduled to be removed in Gradle 5.0. Please see https://docs.gradle.org/4.3.1/userguide/java_plugin.html#sec:java_cross_compilation for more details.

> Configure project :
/home/rdmueller/dt-issue-199/docToolchain/arc42/build/ppt/images

> Task :generateHTML
Converting /home/rdmueller/dt-issue-199/docToolchain/arc42/arc42-template.adoc


BUILD SUCCESSFUL in 25s
1 actionable task: 1 executed
>~/dt-issue-199/docToolchain$

```

**Comment by rdmueller** [comment] 2018-10-08 20:25
hm... I've seen those error messages before...

Could it be that some of the files in the project are locked because they are open in an editor?

    Failed to create MD5 hash for file content.

this sounds like it... Did you maybe open one of the adoc files before you started the `generateHTML` task?

**Comment by Ookami86** [comment] 2019-03-06 14:28
I had the same issue. I suppose Gradle assumes when you're running the Linux executable even in git bash on Windows, you have a file system that dosn't do locking. Long story short, running the docToolchain.bat file solved the issue for me. 
Try running it like this: ./bin/doctoolchain.bat arc42 generateHTML arch-docs generateHTML

**Comment by rdmueller** [comment] 2023-02-18 14:26
I think this is outdated by now, so let's close it.

**Closed by rdmueller** 2023-02-18 14:26 UTC
Labels: 🐞 bug
