### ISSUE TITLE
gradle build fails all tests on V1.0.0

### ISSUE THREAD

**Issue by SoftwareApe** [docToolchain/docToolchain#267] opened 2019-01-30 12:25 UTC
**Describe the bug**
gradle downloads all components but fails all tests.

**To Reproduce**
1. git clone --recurse-submodules <repo>
2. git checkout V1.0.0
3. cd docToolchain
4. gradle build

**Expected behavior**
Gradle builds all modules, executes tests and reports success.

**Screenshots**
```shell
gradle build

> Configure project :

docDir: .

mainConfigFile:
Config.groovy
inputPath: src/docs
inputFiles: [[file:test.adoc, formats:[html, pdf, docbook]], [file:manual.adoc, formats:[html, pdf]], [file:ppt/Demo.pptx.ad, formats:[html, revealjs]]] outputPath: build/docs
./build/docs/ppt/images

> Task :test

docToolchain.ExportChangeLogSpec > test creation of log file FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at ExportChangeLogSpec.groovy:19
docToolchain.ExportMarkdownSpec > test conversion of sample markdown file FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at ExportMarkdownSpec.groovy:20
docToolchain.GenerateDeckSpec > test correct generation of slide deck FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at GenerateDeckSpec.groovy:17
docToolchain.GenerateDeckSpec > test skipped generation of slide deck FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at GenerateDeckSpec.groovy:27
docToolchain.GenerateHTMLSpec > test correct handling of plantUML FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at GenerateHTMLSpec.groovy:22
docToolchain.GeneratePdfSpec > test correct handling of plantUML FAILED org.gradle.testkit.runner.UnexpectedBuildFailure at GeneratePdfSpec.groovy:22
6 tests completed, 6 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
```

**Configuration**
 - OS: Windows 10, gradle via Cntlm proxy

**Additional context**

**Comment by rdmueller** [comment] 2019-01-30 12:37
can you please check the following:

go to the folder /docToolchain/resources

ist the reveal.js project available in the project? Has it been checked out?

**Comment by SoftwareApe** [comment] 2019-01-30 12:56
Hello Ralf,

yes, reveal.js has been checked out. I have in the meantime found that this is again a proxy problem.

The main gradle build uses the proxy that I configured in my gradle.properties in the GRADLE_USER_HOME.

However the tests seem to need some dependencies again which can only be downloaded through the proxy. However they don't look at the same `gradle.properties`.

If I add my proxy options to the `gradle.properties` inside the project then 4 out of 6 tests pass.

```shell
docToolchain.ExportChangeLogSpec > test creation of log file FAILED

    org.gradle.testkit.runner.UnexpectedBuildFailure at ExportChangeLogSpec.groovy:19

docToolchain.GenerateDeckSpec > test correct generation of slide deck FAILED

    org.gradle.testkit.runner.UnexpectedBuildFailure at GenerateDeckSpec.groovy:17


6 tests completed, 2 failed
```

**Comment by SoftwareApe** [comment] 2019-01-30 12:57
I'm not sure why the sub-gradle invocations use a different `gradle.properties`.

**Comment by SoftwareApe** [comment] 2019-01-30 13:30
Btw the documentation seems to generate fine.

**Comment by SoftwareApe** [comment] 2019-01-30 13:38
How many tests pass seems to be quite random. I sometimes get 1, 2, or 3 failures.

**Comment by SoftwareApe** [comment] 2019-01-30 13:45
Found out that UP_TO_DATE means nothing changed. I get success after

```shell
gradle clean
gradle build
```

The tests should either check for up to dateness or success, or they should clean automatically before executing. I don't know how to change this though.

**Comment by rdmueller** [comment] 2019-01-30 19:02
ok. I will now try to reproduce or (even better) try to figure out the steps needed for a stable test. 
Here is my script:

using Java 8, no proxies, graphviz & git installed

```bash
git clone git@github.com:docToolchain/docToolchain.git
cd docToolchain/
git checkout V1.0.0
git submodule update -i
rm -r build
./gradlew clean test --info
```

This now results in no errors on my machine. It is important to run the tests in a defined environment.

The `clean` tasks is not enough to clean up, since it is defined by the java or groovy plugin. The `rm` is on the safe side.

As you've already noticed, when you've already executed tests once, artifacts will remain in the build folder. This results in an "up-to-date" response of the corresponding script (the artifact has already been created).

It is also important to have graphvis installed.

Travis gives us the ideal environment for clean tests.
The travis build can be checked out here for V1.0.0 (I've created a branch):
https://travis-ci.org/docToolchain/docToolchain/builds/486567399

https://github.com/docToolchain/docToolchain/tree/branch_V1.0.0

**Comment by rdmueller** [comment] 2019-01-30 19:02
The travis tests are also green...

**Comment by rdmueller** [comment] 2019-01-30 21:37
I've added a section on how to run the tests in the manual:
https://doctoolchain.github.io/docToolchain/#_development

Feel free to further add your experience.

**Comment by rdmueller** [comment] 2019-03-10 17:26
@SoftwareApe did you have the change to run further tests?

**Comment by rdmueller** [comment] 2019-03-10 17:27
@SoftwareApe did you have the change to run further tests?

**Comment by rdmueller** [comment] 2019-05-19 17:07
Tests have been brushed up lately. They are all green for the current master and docToolchain even runs with JDK11 (and is tested with it through travis)
So, I will close this ticket

**Closed by rdmueller** 2019-05-19 17:07 UTC
