### ISSUE TITLE
exportContributors script fails

### ISSUE THREAD

**Issue by ewoks** [docToolchain/docToolchain#465] opened 2020-08-24 17:33 UTC
**Describe the bug**
As described in a PR template, I tried to update documentation but `/scripts/exportContributors.gradle` failed at line 49.

**To Reproduce**
1. execute  `./gradlew exportContributors && ./gradlew && ./copyDocs.sh` like PR template recommends.
2. See error:

```
> Task :exportContributors FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/ewoks/docs-as-code/docToolchain-Ewoks-Fork/scripts/exportContributors.gradle' line: 49

* What went wrong:
Execution failed for task ':exportContributors'.
> java.io.FileNotFoundException: /home/ewoks/docs-as-code/docToolchain-Ewoks-Fork/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/build/docs/contributors/src/docs/manual/06_Frequently_asked_Questions.adoc 
(File name too long)

```

**Expected behavior**
Export contributors script shouldn't failed because of multiple stacked path bug 

**Screenshots**
![Screenshot from 2020-08-24 19-59-02](https://user-images.githubusercontent.com/1666500/91079474-5ebf9580-e644-11ea-90d2-d6183b4a57fb.png)

**Configuration**
 - OS: **Linux**

**Comment by ewoks** [comment] 2020-08-24 18:01
It seems that `tag` variable at line 46 
`def tag = (file.canonicalPath - sourceFolder.canonicalPath).replace("\\", "/").replaceAll("^/", "")`
is getting bigger and bigger with every iteration until it hits the filesystem path limit so few lines later file can't be created and script fails.

It is funny bug (see nested files on screenshot above), but I'm curious if someone can reproduce this on Windows machines :) 

cc: @rdmueller

**Comment by rdmueller** [comment] 2020-08-24 19:05
hm. I already noticed that this is not really stable, but didn't take the time to analyze it.

I normally use the gitpod.io environment and run the scripts there. As far as I know, it runs well there ("runs on my machine" :-)

https://gitpod.io/#https://github.com/docToolchain/docToolchain

Will take a closer look as soon as the last PR is ready to be merged

**Comment by rdmueller** [comment] 2020-08-24 19:50
when we fix this, we should also check https://github.com/docToolchain/docToolchain/issues/260

**Comment by rdmueller** [comment] 2020-08-24 20:11
hm. I just managed to regenerate the docs with gitpod. But somehow I had to run the exportContributors twice...

**Comment by ewoks** [comment] 2020-08-24 20:37
yeah added screenshot up there, on my machine was reproducible always, now I am curious to see on which iteration fails :clown_face:

**Comment by rdmueller** [comment] 2020-08-25 19:16
hm. Can you please try to reproduce your problem with gitpod?
https://gitpod.io/#https://github.com/docToolchain/docToolchain

I can't reproduce your problem, but I see the problem that the result of `exportContributors` gets deleted afterwards... can't find why

**Closed** 2020-10-12 21:23 UTC
