### ISSUE TITLE
Build suddenly fails (since changes to Gradle plugin portal)

### ISSUE THREAD

**Issue by eNBeWe** [docToolchain/docToolchain#1414] opened 2024-07-16 10:31 UTC
**Describe the bug**
docToolchain can't resolve all dependencies anymore:

```
09:46:44  + ./dtcw local install doctoolchain
09:46:44  dtcw 0.51 - ##DTCW_GIT_HASH##
09:46:44  docToolchain 3.3.1
09:46:44  OS/arch: Linux/x86_64
09:46:44  Available docToolchain environments: local
09:46:44  Environments with docToolchain [3.3.1]: none
09:46:44  Using environment: local
09:46:44    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
09:46:44                                   Dload  Upload   Total   Spent    Left  Speed
09:46:45  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
09:46:46  
 13 22.8M   13 3229k    0     0  3220k      0  0:00:07  0:00:01  0:00:06 3220k
100 22.8M  100 22.8M    0     0  17.6M      0  0:00:01  0:00:01 --:--:-- 66.9M
09:46:46  Installed docToolchain successfully in '/home/user1001/.doctoolchain/docToolchain-3.3.1'.
09:46:46  Using Java 17.0.10 [/opt/java/openjdk/bin/java]
09:46:46  
09:46:46  Use './dtcw tasks --group doctoolchain' to see docToolchain related tasks.
09:46:46  
09:46:46  [Pipeline] }
09:46:46  [Pipeline] // dir
09:46:46  [Pipeline] }
09:46:46  [Pipeline] // stage
09:46:46  [Pipeline] stage
09:46:46  [Pipeline] { (Build Documentation)
09:46:46  [Pipeline] dir
09:46:46  Running in ...
09:46:46  [Pipeline] {
09:46:46  [Pipeline] sh
09:46:47  + ./dtcw collectIncludes generateHTML generatePDF
09:46:47  dtcw 0.51 - ##DTCW_GIT_HASH##
09:46:47  docToolchain 3.3.1
09:46:47  OS/arch: Linux/x86_64
09:46:47  Available docToolchain environments: local
09:46:47  Environments with docToolchain [3.3.1]: local
09:46:47  Using environment: local
09:46:47  Using Java 17.0.10 [/opt/java/openjdk/bin/java]
09:46:47  Using headless mode since there is no (terminal) interaction possible
09:46:47  Downloading https://services.gradle.org/distributions/gradle-8.1.1-bin.zip
09:46:50  ...........10%............20%............30%............40%............50%............60%............70%............80%...........90%............100%
09:46:52  
09:46:52  Welcome to Gradle 8.1.1!
09:46:52  
09:46:52  Here are the highlights of this release:
09:46:52   - Stable configuration cache
09:46:52   - Experimental Kotlin DSL assignment syntax
09:46:52   - Building with Java 20
09:46:52  
09:46:52  For more details see https://docs.gradle.org/8.1.1/release-notes.html
09:46:52  
09:46:52  To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
09:46:54  Daemon will be stopped at the end of the build 
09:47:21  
09:47:21  FAILURE: Build failed with an exception.
09:47:21  
09:47:21  * Where:
09:47:21  Build file '/home/user1001/.doctoolchain/docToolchain-3.3.1/build.gradle' line: 98
09:47:21  
09:47:21  * What went wrong:
09:47:21  A problem occurred evaluating root project 'docToolchain'.
09:47:21  > Could not resolve all files for configuration 'classpath'.
09:47:21     > Could not find org.ysb33r.gradle:grolifant:0.12.
09:47:21       Searched in the following locations:
09:47:21         - https://plugins.gradle.org/m2/org/ysb33r/gradle/grolifant/0.12/grolifant-0.12.pom
09:47:21       If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
09:47:21       Required by:
09:47:21           unspecified:unspecified:unspecified > org.asciidoctor:asciidoctor-gradle-jvm-gems:4.0.0-alpha.1 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2
09:47:21     > Could not find com.burgstaller:okhttp-digest:1.10.
09:47:21       Searched in the following locations:
09:47:21         - https://plugins.gradle.org/m2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
09:47:21       If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
09:47:21       Required by:
09:47:21           unspecified:unspecified:unspecified > org.asciidoctor:asciidoctor-gradle-jvm-gems:4.0.0-alpha.1 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2 > io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3
09:47:21  
09:47:21  * Try:
09:47:21  > Run with --stacktrace option to get the stack trace.
09:47:21  > Run with --info or --debug option to get more log output.
09:47:21  > Run with --scan to get full insights.
09:47:21  
09:47:21  * Get more help at https://help.gradle.org/
09:47:21  
09:47:21  BUILD FAILED in 31s
```

**To Reproduce**
1. Run docToolchain 3.3.1 on a clean workspace
2. See error

**Expected behavior**
docToolchain works properly.

**Configuration**
 - docToolchain version 3.3.1
 - OS: Linux / Jenkins
 - Relevant SDK Versions JDK 17

**Additional context**
The issue seems to be related to changes in Gradle Plugin Portal:
> The Gradle Plugin Portal will continue to return redirects (303 See Other) for artifact queries it cannot serve. Starting July 15, 2024, these redirects will be towards [Maven Central](https://repo.maven.apache.org/maven2) instead of JCenter.

**Comment by rdmueller** [comment] 2024-07-16 11:26
I love those breaking changes! Not!

**Comment by lyca** [comment] 2024-07-16 11:55
I was bitten by the same problem today, so I started looking over the dependencies. It seems, that the dependencies in regards to the [asciidoctor-gradle-plugin](https://github.com/docToolchain/docToolchain/blob/ng/libs.versions.toml#L11) need to be updated. In the final 4.0.0 release of the asciidoctor-gradle-plugin the JCenter problems were handled ([details](https://github.com/asciidoctor/asciidoctor-gradle-plugin/commit/6157479f06b6ffc54021ab814b8ce0ef82598710)).
So an update to asciidoctor-gradle-plugin 4.0.2 should solve the resolution issue, but there could be some other breaking stuff :thinking:

**Comment by rdmueller** [comment] 2024-07-16 12:02
there is breaking stuff. That's why we are still on the older version.
We already had a fix in place in the past. At least for the grolifant:

https://github.com/docToolchain/docToolchain/blob/ng/build.gradle#L12

I now try to get this back up and running

**Comment by rdmueller** [comment] 2024-07-16 13:00
hm. this old fix does not work anymore!

https://github.com/docToolchain/docToolchain/issues/1200#issuecomment-1604705324

don't know why. The `build.gradle` which contains the fix is executed, but the fix does not work

**Comment by rdmueller** [comment] 2024-07-16 13:01
Workaround for the moment: the docker image for 2.2.1 should be self-contained

**Comment by ashauer** [comment] 2024-07-16 14:36
We had the same problem in our CI starting today, too. That is, using the DTC Docker image. But I could not reproduce it locally.

In our case we had configured  _mavenRepository_, _mavenUsername_ and _mavenPassword_ in the CI to make the DTC use an internal cache instead of pulling from the internet. I now removed this additional configuration and the jobs work again! Well, at least currently the do.

I don't know exactly how Gradle works when resolving dependencies. A wild guess is that it checks the local cache where those artifacts come from, and if you reconfigure the maven repo to another source, Gradle maybe tries to fetch the dependencies again from there? I have that suspicion because my local run in debug mode showed that Gradle uses the dependencies from within the image (checked especially with the two artifacts mentioned above which were the problem in our case as well).

Maybe this information helps finding what the actual issue is and fixing it...

**Comment by rdmueller** [comment] 2024-07-17 09:22
so, the workaround I have tried do not solve the problem. Only partly. So now I try to locally resolve the needed dependencies, but also do not succeed. I am unable to configure the gradle build in such a way that it fetches the local jars :-o

**Comment by rdmueller** [comment] 2024-07-17 10:04
It seems that I found a solution. stay tuned.

**Comment by rdmueller** [comment] 2024-07-17 13:38
so, for a fix, we need

* use a newer version of grolifant which is also found on maven central
* okhttp-digest had a name change when it was moved to maven central and we also need to use a newer version

these changes need to be implented in `/scripts/AsciiDocBasics.gradle` as shown in this PR: 

https://github.com/docToolchain/docToolchain/pull/1416

now, a problem with markdown_to_asciidoc popped up which I had not locally, so I am still fixing things...

**Comment by rdmueller** [comment] 2024-07-17 15:45
So, I managed to upgrade the markdown_to_asciidoc library, but it needs a JDK v17 ...

**Comment by rdmueller** [comment] 2024-07-17 17:01
build is green, tests are green. let's create a new release ... tomorrow

**Comment by lyca** [comment] 2024-07-17 18:51
Great news, many thanks for your efforts :+1:

**Comment by rdmueller** [comment] 2024-07-18 06:23
still have to create a release...

**Comment by rdmueller** [comment] 2024-07-18 12:31
a new release v3.4.0 is available as local install and as docker image.

Can you please  give it a try? You have to update the version in your dtcw file manually.

**Comment by eNBeWe** [comment] 2024-07-18 14:36
Seems to work fine. Thank you.

**Comment by rdmueller** [comment] 2024-07-18 15:34
Great. Thanx for testing. So, I will finish the release tomorrow and close this issue.

**Comment by rdmueller** [comment] 2024-07-19 09:57
release finished

**Closed as completed by rdmueller** 2024-07-19 09:57 UTC
