### ISSUE TITLE
Docs: Feedback for 'publishToConfluence' 👎

### ISSUE THREAD

**Issue by apparatchick** [docToolchain/docToolchain#1006] opened 2023-02-01 13:40 UTC
Hi, I wish to publish from a Mac to Confluence Data Center. I have a Personal Access Token in place. What should I type in the Terminal? Something like this: "./dtcw publishToConfluence -Pname=tokenname -Ptoken=tokenstring". 

---
#page:015_tasks/03_task_publishToConfluence.adoc

**Comment by ghost** [comment] 2023-02-06 09:35
I think this question is a duplicate of https://github.com/docToolchain/docToolchain/issues/992

**Comment by apparatchick** [comment] 2023-02-08 10:27
Thank you for answering. The question is similar, but the previous question does not really provide an actionable answer. I have meanwhile found the answer for my more specific question. It is putting bearerToken = "${new File("/Users/miranda/personalaccesstoken").text}" in the docToolchainConfig.groovy file. What does not work in this case is apitoken = "${new File("/Users/me/personalaccesstoken").text}". The referenced file is stored outside the project repository and contains the Confluence PAT. You must also include  credentials = "${new File("/Users/me/credentials").text}".bytes.encodeBase64().toString() in docToolchainConfig.groovy and store the credentials also outside of the project repo. The file contains a "user:password" string.

**Closed as completed** 2023-02-08 10:27 UTC
