### ISSUE TITLE
collectIncludes wrong path int resulting file when using scanDir

### ISSUE THREAD

**Issue by dcherix** [docToolchain/docToolchain#624] opened 2021-09-06 12:15 UTC
**Describe the bug**
When setting a value for scanDir, the path to the collected files doesn't contains the scanDir part.

**To Reproduce**
setting scanDir to docs/adr
files to collect are in the dir docs/adr

**Expected behavior**
The resulting includes in the generated file should contains the docs/adr part in the path

**Screenshots**
`../build/docs/_includes/ADR_includes.adoc: line 2: include file not found: /project/ADR_0001-record-architecture-decisions.adoc
`

**Configuration**
- problems occurs when running the docker image with version: v2.0.0-rc14c

**Comment by rdmueller** [comment] 2021-09-06 13:35
can you send the log output?
and could you run it with the `--info` option?

Do you set the scanDir to `docs/adr` or `./docs/adr`?

**Comment by dcherix** [comment] 2021-09-06 13:55
Here is the log output, I've set scanDir to `./docs/adr`
` doctoolchain . collectIncludes generateHtml -PinputPath=docs -PscanDir=./docs/adr -PmainConfigFile=docs/docToolchain.groovy -PtargetDir=/build/docs --info
Initialized native services in: /home/dtcuser/.gradle/native
The client will now receive all logging from the daemon (pid: 83). The daemon log file: /home/dtcuser/.gradle/daemon/6.7.1/daemon-83.out.log
Starting 13th build in daemon [uptime: 1 hrs 6 mins 10.89 secs, performance: 100%]
Using 6 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file '/home/dtcuser/docToolchain/settings.gradle'.
Projects loaded. Root project using build file '/home/dtcuser/docToolchain/build.gradle'.
Included projects: [root project 'docToolchain']

> Configure project :
Evaluating root project 'docToolchain' using build file '/home/dtcuser/docToolchain/build.gradle'.
[Asciidoctor] asciidoctorj: 1.6.2
[Asciidoctor] asciidoctorj-groovy-dsl: 1.6.0
docToolchain> docDir: /project
docToolchain> mainConfigFile: docs/docToolchain.groovy
docToolchain> pdfThemeDir: 
docToolchain> inputPath: docs

Gradle project Properties [5]:
[inputPath:docs, scanDir:./docs/adr, mainConfigFile:docs/docToolchain.groovy, docDir:/project, targetDir:/build/docs]
==============================
Found passed Jira credentials
docToolchain> referenceDocFile: 

==================
Parsed config file has 17 entries

Found config -> 'outputPath': 'build/docs'
Found config -> 'inputPath': 'docs'
Found config -> 'inputFiles': '[[file:notificationsservice.adoc, formats:[html, pdf]]]'
Found config -> 'taskInputsDirs': '[docs/images]'
Found config -> 'taskInputsFiles': '[]'
Found config -> 'changelog.dir': 'docs'
Found config -> 'changelog.cmd': 'git log --pretty=format:%x7c%x20%ad%x20%n%x7c%x20%an%x20%n%x7c%x20%s%x20%n --date=short'
Found config -> 'confluence.input': '[[file:build/docs/html5/notificationsservice.html, ancestorId:*******]]'
Found config -> 'confluence.api': '*********
Found config -> 'confluence.spaceKey': 'null'
Found config -> 'confluence.createSubpages': 'false'
Found config -> 'confluence.preambleTitle': 'NotificationsService'
Found config -> 'confluence.pagePrefix': ''
Found config -> 'confluence.pageSuffix': ''
Found config -> 'confluence.credentials': '********'
Found config -> 'confluence.extraPageContent': '<ac:structured-macro ac:name="warning"><ac:parameter ac:name="title" /><ac:rich-text-body>This is a generated page, do not edit!</ac:rich-text-body></ac:structured-macro>'
Found config -> 'jira.credentials': '********'
notificationsservice.adoc
/project/build/docs/images
docToolchain> docDir: /project
docToolchain> mainConfigFile: docs/docToolchain.groovy
docToolchain> pdfThemeDir: 
docToolchain> HSC sourceDir: /project/build/docs/html5
docToolchain> HSC checkingResultsDir: /project/build/docs/report/htmlchecks

---> OpenAPI specification file not found in Config.groovy (https://doctoolchain.github.io/docToolchain/#_exportopenapi)
You are using one or more deprecated Asciidoctor Gradle plugin features. To help with migration run with --warning-mode=all.
All projects evaluated.
Selected primary task 'collectIncludes' from project :
Selected primary task 'generateHTML' from project :
Tasks to be executed: [task ':collectIncludes', task ':generateHTML']
Tasks that were excluded: []
:collectIncludes (Thread[Execution worker for ':',5,main]) started.

> Task :collectIncludes
Caching disabled for task ':collectIncludes' because:
  Build cache is disabled
Task ':collectIncludes' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
docToolchain> docDir: /project
docToolchain> scanDir: ./docs/adr
docToolchain> scanDir: /project/docs/adr
docToolchain> includeRoot: .
docToolchain> includeRoot: /project
sourceFolder: /project/docs/adr
file: /project/docs/adr/ADR_0003-using-sprinmvc-vs-webflux.adoc
corrected file: ADR_0003-using-sprinmvc-vs-webflux.adoc
file: /project/docs/adr/ADR_0000-adr-template.adoc
ignore template file: ADR_0000-adr-template.adoc
file: /project/docs/adr/ADR_0001-record-architecture-decisions.adoc
corrected file: ADR_0001-record-architecture-decisions.adoc
file: /project/docs/adr/ADR_0002-using-kotlin.adoc
corrected file: ADR_0002-using-kotlin.adoc
file: /project/docs/adr/ADR_0004-SignalR-servicemode.adoc
corrected file: ADR_0004-SignalR-servicemode.adoc
targetDir - docDir: /build/docs
targetDir - includeRoot: /build/docs
pathDiff: ../../
/project/build/docs/_includes/ADR_includes.adoc
:collectIncludes (Thread[Execution worker for ':',5,main]) completed. Took 0.034 secs.
:generateHTML (Thread[Execution worker for ':',5,main]) started.

> Task :generateHTML UP-TO-DATE
Caching disabled for task ':generateHTML' because:
  Build cache is disabled
Skipping task ':generateHTML' as it is up-to-date.
:generateHTML (Thread[Execution worker for ':',5,main]) completed. Took 0.068 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 982ms
2 actionable tasks: 1 executed, 1 up-to-date
`

**Comment by rdmueller** [comment] 2021-09-06 20:36
thanx for the log output.

hm. I guess I see the problem. 
Interesting to see that you use rc14c without the doctoolchain wrapper (dtcw)
https://doctoolchain.github.io/docToolchain/v2.0.x/#_how_to_install_doctoolchain

Regarding your problem: I think the problem is somewhere near this line:
https://github.com/docToolchain/docToolchain/blob/master/scripts/collectIncludes.gradle#L66

will take a closer look at it tomorrow.

**Comment by mh182** [comment] 2023-04-27 05:50
@rdmueller Can we close this issue?

**Comment by mh182** [comment] 2023-05-04 06:14
@PacoVK You made a change to `collectIncludes` with 8061694f. Do you know if we can close this issue?

**Closed** 2023-05-08 20:11 UTC
